Configure travis
ChShersh/haskell-course-assistant pull request #12
Opened 2018-06-04 15:25 UTC by NatalyaSlepkova

Resolves #10

2018-06-05 04:51 UTC, ChShersh commented
Thanks for your contribution! Could you please use `.travis.yml` config like in this repository?

* https://github.com/kowainik/summoner

Also, I've activated Travis CI for this repo, you should be able to see statuses for new commits.

2018-06-07 01:44 UTC, ChShersh commented
@NatalyaSlepkova It's better to if you just copy `.travis.yml` from `summoner` project and change name of the project. And remove `notifications:` section. If doesn't work, I will look into it.

2018-06-07 01:47 UTC, chshersh requested changes
Almost there, but config requires some changes.

2018-06-07 01:47 UTC, ChShersh commented on .travis.yml
> +language: generic
This should be `haskell` instead of `generic`

2018-06-07 01:47 UTC, ChShersh commented on .travis.yml
> +  - "$HOME/build/NatalyaSlepkova/haskell-course-assistant/.stack-work"
User name should be `ChShersh` instead of `NatalyaSlepkova` because it will eventually run under my Travis account.

2018-06-07 01:47 UTC, ChShersh commented on .travis.yml
> +    env: GHCVER='8.2.2' STACK_YAML="$HOME/build/NatalyaSlepkova/haskell-course-assistant/stack.yaml"
My GitHub login here as well.

2018-06-07 01:47 UTC, ChShersh commented on .travis.yml
> +- stack --no-terminal --install-ghc test --only-dependencies
This section doesn't look the same as for `summoner` project.

2018-06-07 01:47 UTC, ChShersh commented on .travis.yml
> +- stack --no-terminal test --haddock --no-haddock-deps
Also, doesn't look the same as for `summoner` project.

2018-06-07 01:47 UTC, ChShersh commented on README.md
> +[![Build Status](https://travis-ci.org/ChShersh/haskell-course-assistant.svg?branch=master)](https://travis-ci.org/ChShersh/haskell-course-assistant)
Thanks for adding badge!

2018-06-10 06:02 UTC, chshersh approved these changes

2018-06-10 06:03 UTC, merged